DELETE FROM Toy;
DELETE FROM Child;
DELETE From Lootbag;

DROP TABLE IF EXISTS Toy;
DROP TABLE IF EXISTS Child;
DROP TABLE IF EXISTS Lootbag;

CREATE TABLE `Lootbag` (
    `LootbagId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name` TEXT NOT NULL
);

CREATE TABLE `Child` (
    `ChildId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name` TEXT NOT NULL,
    `DeliveryStatus` INTEGER NOT NULL,
    `LootbagId` INTEGER NOT NULL,
    FOREIGN KEY(`LootbagId`) REFERENCES `Lootbag`(`LootbagId`)
);

CREATE TABLE `Toy` (
    `ToyId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name` TEXT NOT NULL,
    `ChildId` INTEGER NOT NULL,
    FOREIGN KEY(`ChildId`) REFERENCES `Child`(`ChildId`)
);
